name: surveymyboatpro
description: Survey My Boat Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: '3.24.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme:
  cupertino_icons:
  flutter_bloc:
  equatable:
  pdf:
  printing:
  dart_json_mapper:
  expansion_tile_card:
  http:
  device_preview:
  getwidget:
  flutter_form_builder:
  get:
  form_builder_validators:
  intl:
  string_2_icon:
  intl_utils:
  pattern_formatter:
  http_certificate_pinning:
  bloc_concurrency:
  modbus_client_tcp:
  custom_navigation_bar:
  flutter_inappwebview:
  animated_toggle_switch:
  reflectable:
  glob:
  get_storage:
  shared_preferences:
  uuid: ^4.5.1
  rate_my_app: ^2.2.0
  firebase_analytics: ^11.3.4
  firebase_core: ^3.7.0
  google_mobile_ads: ^5.2.0
  connectivity: ^3.0.6
  encrypt: ^5.0.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  test: ^1.25.8
  bloc_test: ^9.1.7
  mockito: ^5.4.4

flutter_secure_storage:
  enabled: true
  class_name: SecureStorage
  main_locale: en

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
    - assets/images/

