name: surveymyboatpro
description: Survey My Boat Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: '3.24.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme:
  cupertino_icons:
  flutter_bloc:
  equatable:
  pdf:
  printing:
  dart_json_mapper:
  expansion_tile_card:
  http:
  device_preview:
  getwidget:
  flutter_form_builder:
  get:
  form_builder_validators:
  intl:
  string_2_icon:
  intl_utils:
  pattern_formatter:
  http_certificate_pinning:
  bloc_concurrency:
  modbus_client_tcp:
  custom_navigation_bar:
  flutter_inappwebview:
  animated_toggle_switch:
  reflectable:
  glob:
  get_storage:
  shared_preferences:
  uuid: ^4.5.1
  rate_my_app: ^2.2.0
  encrypt: ^5.0.3
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  wiredash: ^2.3.0
  video_player: ^2.9.2
  animations: ^2.0.11
  flutter_markdown: ^0.7.4+1
  font_awesome_flutter: ^10.8.0
  mask_text_input_formatter: ^2.9.0
  about: ^2.2.0
  multiselect_formfield: ^0.1.7
  pdfx: ^2.8.0
  signature: ^5.5.0
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  test: ^1.25.7
  bloc_test: ^9.1.7
  mockito: ^5.4.4

flutter_secure_storage:
  enabled: true
  class_name: SecureStorage
  main_locale: en

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/mock/
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/help/
    - assets/fonts/
    - assets/locale/i18n_en.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf